// src/lib/components/hero.svelte
<script>
	import hero from '$lib/assets/hero-1.jpg'
</script>

<section class="relative w-full h-screen">
	<img
		src={hero}
		alt=""
		class="w-full h-full object-cover object-[80%]
lg:object-center"
	/>
	<div
		class="flex absolute inset-0 justify-center items-center text-white bg-gradient-to-b prose-xl font-fancy from-slate-900/60 to-slate-900/20"
	>
		<div class="z-50 pt-10 pr-14 w-10/12 cursor-default md:p-0 md:w-7/12">
			<h1 class="hero-heading">I&apos;m Marius Nilsen Kluften.</h1>
			<h2 class="flex flex-col flex-wrap mt-8">
				<span>
					A<span class="inline-block px-1 mx-3 bg-white hover:animate-ping text-main">
						web
					</span>developer based in Oslo.
				</span>
				<span>
					Working for Dr.Dropin, crafting
					<span
						class="inline-block px-1 mx-3 mr-2 bg-white transition text-accent hover:motion-safe:animate-spin"
					>
						<span class="block">sweet</span>
					</span>
					web apps.
				</span>
			</h2>
		</div>
	</div>
</section>

// src/components/Hero/Hero.tsx
import { isClient } from '@utils/environment'
import { useRef } from 'react'
import Xarrow from 'react-xarrows'
import HeroImage from './HeroImage'

const Hero = () => {
  const ref = useRef(null)
  return (
    <section className="relative w-full h-screen">
      <HeroImage />
      <div className="absolute inset-0 flex items-center justify-center prose-xl text-white font-fancy bg-slate-900/80">
        <div className="w-10/12 md:w-7/12 cursor-default pr-14 pt-10 md:p-0 z-50">
          <div className="w-20 h-20" ref={ref}></div>
          <div className="pb-">I&apos;m</div>
          <h1 className="hero-heading">Marius Nilsen Kluften</h1>
          <h2 className="flex flex-wrap mt-8">
            <span className="border-b-x">
              A
              <div className="mx-3 inline-block hover:animate-ping text-main bg-white px-1">
                web
              </div>
              developer based in Oslo.
            </span>
            <span>
              Working for DrDropin, crafting
              <div className="mx-3 hover:motion-safe:animate-spin  mr-2 text-accent inline-block  bg-white transition px-1">
                <span className="block">sweet</span>
              </div>
              web apps.
            </span>
          </h2>
        </div>
        {isClient && (
          <Xarrow
            start={ref}
            end="my-face"
            endAnchor="top"
            startAnchor="right"
            animateDrawing={0.8}
            _cpx1Offset={100}
            _cpy1Offset={-200}
            _cpy2Offset={-100}
          />
        )}
      </div>
    </section>
  )
}

export default Hero
